server:
  port: 8080


spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: d2456e0d3f62d5838fb2
            clientSecret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
          qq:
            clientId: qqe
            clientSecret: 32

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pass123


## Mybatis
mybatis:
  mapper-locations: classpath*:mappers/*.xml

jwt:
  secret: ji934fsfS9fA01eoPq23
  expiration: 3600000
  header: JWTHeaderName

oauth-client:
  github:
    client-id: d2456e0d3f62d5838fb2
    client-secret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
    access-token-uri: https://github.com/login/oauth/access_token
    user-authorization-uri: https://github.com/login/oauth/authorize
    resource:
      user-info-uri: https://api.github.com/user

debug: true